### PR TITLE
yapf

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**

### CODE REVIEW

**Comment by krenzland** [comment]
Is yapf deterministic? I.e. does yapf(yapf(code)) produce the same result as yapf(code)?
I'm asking because I've heard that it isn't. Apparently the tool black is but I'm also not sure about that.

**Comment by Thomas-Ulrich** [comment]
Yeah, I also read that.
But maybe they fixed it since then?
At least when when I apply yapf on the repository again, it does not produce new changes, and the git action works fine.
Personally, I have good experience with black on my private repository. But I agree that yapf produces nicer code.
I would try yapf and if it's the source of troubles blame @uphoffc who brought that up :-)

**Comment by uphoffc** [comment]
Independent of the tool, do we think that automatic formatting on commit is a good idea? (Or is it just a check?)

**Comment by Thomas-Ulrich** [comment]
That's just a check

**Comment by Thomas-Ulrich** [comment]
here is an example https://github.com/Thomas-Ulrich/test0000/pull/2

**Pull request closed without merging**
